<#
.SYNOPSIS
  falsify-lab launcher (Windows native, Omnigent 0.16.0).

.DESCRIPTION
  -Setup     uv sync project venv; render MCP sidecars with absolute paths.
             -RunsDir names the prepared DEMO CAMPAIGN ROOT the MCP tools act on
             (FALSIFY_RUNS_DIR); re-run -Setup (and restart -Server) for a new root.
  -Prepare   demo-prepare that root (preflight, calibration, seed 1001 initial 3; no LLM).
             The campaign's 60-minute wall cap starts here.
  -Validate  parse + validate the agent bundle with the installed Omnigent
  -Smoke     offline deterministic smoke (ngspice, no LLM)
  -Server    start hidden detached server + host (loopback); registers falsify_supervisor
  -Status    show server status
  -Stop      stop the server/host started by -Server
  -Live      one bounded live supervisor session via scripts\run_live.py (omnigent_client SDK);
             coordinator-operated
  -Run       start one free-form supervisor session; pass -Prompt "<text>"

  All Omnigent state goes to .omnigent-runtime\ inside this project. API-key
  env vars are removed from THIS process only so the claude-sdk harness uses the
  existing Claude Code subscription login instead of a paid API key.
#>
[CmdletBinding()]
param(
    [switch]$Setup,
    [switch]$Validate,
    [switch]$Smoke,
    [switch]$Server,
    [switch]$Status,
    [switch]$Run,
    [switch]$Stop,
    [switch]$Prepare,
    [switch]$Live,
    [string]$Prompt = "",
    [int]$Port = 6767,
    [string]$RunsDir = 'runs\demo\live-1001'
)
$ErrorActionPreference = 'Stop'
$Root = $PSScriptRoot
$OmniVersion = '0.16.0'
$OmniPython = Join-Path $env:APPDATA 'uv\tools\omnigent\Scripts\python.exe'
$VenvPython = Join-Path $Root '.venv\Scripts\python.exe'
$Agent = Join-Path $Root 'agent'

# --- process-scoped environment (never persisted) ---------------------------
$Runtime = Join-Path $Root '.omnigent-runtime'
New-Item -ItemType Directory -Force $Runtime | Out-Null
$env:OMNIGENT_DATA_DIR = $Runtime
$env:OMNIGENT_CONFIG_HOME = $Runtime
$env:OMNIGENT_NO_UPDATE_CHECK = '1'
$env:OMNIGENT_HOST_NO_OPEN = '1'
$env:OMNIGENT_DISABLE_TELEMETRY = '1'
$env:DO_NOT_TRACK = '1'
# Korean cp949 console codepage breaks Omnigent's host tunnel (UnicodeEncodeError on '\u2713').
$env:PYTHONUTF8 = '1'
# Keep claude.ai account connectors (Drive, Docs, ...) out of the agents' Claude CLI tool surface.
$env:ENABLE_CLAUDEAI_MCP_SERVERS = 'false'
# The host daemon forwards only allow-listed env to runners; this is Omnigent's documented passthrough.
$env:OMNIGENT_RUNNER_ENV_PASSTHROUGH = 'ENABLE_CLAUDEAI_MCP_SERVERS'
$env:PYTHONIOENCODING = 'utf-8'
# Hide the npm global bin (codex CLI) from Omnigent: otherwise the host daemon's native-Codex
# model probe copies ~/.codex/auth.json into ~/.omnigent/cache on Windows (symlink not permitted).
$NpmBin = Join-Path $env:APPDATA 'npm'
$env:PATH = (($env:PATH -split ';') | Where-Object { $_ -and ($_.TrimEnd('\') -ne $NpmBin) }) -join ';'
$env:FALSIFY_RUNS_DIR = Join-Path $Root $RunsDir
foreach ($k in 'ANTHROPIC_API_KEY', 'ANTHROPIC_AUTH_TOKEN', 'OPENAI_API_KEY') {
    Remove-Item "Env:$k" -ErrorAction SilentlyContinue
}

function Assert-Omnigent {
    $v = (& omni --version) 2>&1 | Out-String
    if ($v -notmatch [regex]::Escape("omnigent $OmniVersion")) {
        throw "Expected omnigent $OmniVersion, got: $v. Install: uv tool install --python 3.12 omnigent==$OmniVersion"
    }
}

function Write-Sidecar([string]$AgentName, [string[]]$Tools) {
    $dir = Join-Path $Agent "agents\$AgentName\tools\mcp"
    New-Item -ItemType Directory -Force $dir | Out-Null
    $py = ($VenvPython -replace '\\', '/')
    $srv = ((Join-Path $Root 'falsify_lab\mcp_server.py') -replace '\\', '/')
    $runs = ((Join-Path $Root $RunsDir) -replace '\\', '/')
    $ngspiceLine = ''
    if ($env:FALSIFY_NGSPICE) { $ngspiceLine = "`n  FALSIFY_NGSPICE: `"$($env:FALSIFY_NGSPICE -replace '\\', '/')`"" }
    # FALSIFY_MCP_ROLE selects the server-side tool set and the 'Omnigent <role>' ledger actor.
    $yaml = @"
# GENERATED by launch.ps1 -Setup (absolute paths: Omnigent does not expand command/args).
name: falsify
transport: stdio
command: "$py"
args: ["$srv"]
env:
  FALSIFY_RUNS_DIR: "$runs"
  FALSIFY_MCP_ROLE: "$AgentName"$ngspiceLine
timeout: 120
tools: [$($Tools -join ', ')]
"@
    Set-Content -Path (Join-Path $dir 'falsify.yaml') -Value $yaml -Encoding utf8
}

if ($Setup) {
    uv sync --project $Root --python 3.12 --locked 2>$null
    if ($LASTEXITCODE -ne 0) { throw 'Locked dependency setup failed; inspect uv output before changing the lockfile.' }
    Write-Sidecar 'experimenter' @('simulate_pvt_point', 'read_result')
    Write-Sidecar 'analyst' @('analyze_and_plan', 'read_result')
    Write-Host "Setup done. Sidecars rendered under agent\agents\*\tools\mcp\falsify.yaml (demo root $RunsDir)"
}

if ($Prepare) {
    Push-Location $Root
    try { & $VenvPython -m falsify_lab.cli demo-prepare --root (Join-Path $Root $RunsDir); if ($LASTEXITCODE) { throw 'demo-prepare failed' } }
    finally { Pop-Location }
}

if ($Validate) {
    Assert-Omnigent
    Push-Location $Root
    try { & $OmniPython (Join-Path $Root 'scripts\validate_agent.py') $Agent; if ($LASTEXITCODE) { throw 'agent validation failed' } }
    finally { Pop-Location }
}

if ($Smoke) {
    & $VenvPython (Join-Path $Root 'scripts\offline_smoke.py'); if ($LASTEXITCODE) { throw 'offline smoke failed' }
}

if ($Server) {
    Assert-Omnigent
    $pidFile = Join-Path $Runtime 'falsify-pids.json'
    $omniExe = (Get-Command omni).Source
    # Foreground `omni server` in a hidden detached process: unlike `--background`, the
    # foreground path honors --agent, so falsify_supervisor appears in the UI agent picker.
    # Loopback only.
    $srvLog = Join-Path $Runtime 'server-foreground.log'
    $s = Start-Process -FilePath $omniExe -WindowStyle Hidden -PassThru `
        -ArgumentList @('server', '--host', '127.0.0.1', '--port', "$Port", '--agent', "`"$Agent`"") `
        -RedirectStandardOutput $srvLog -RedirectStandardError "$srvLog.err"
    $deadline = (Get-Date).AddSeconds(90)
    do { Start-Sleep -Seconds 2; $ok = (curl.exe -s "http://127.0.0.1:$Port/health") -match '"ok"' } until ($ok -or (Get-Date) -gt $deadline)
    if (-not $ok) { throw "server did not become healthy; see $srvLog(.err)" }
    # Hidden foreground `omni host`: an auto-spawned daemon allow-lists its env and drops
    # ENABLE_CLAUDEAI_MCP_SERVERS; this process keeps it and forwards it to runners via
    # OMNIGENT_RUNNER_ENV_PASSTHROUGH.
    $hostLog = Join-Path $Runtime 'host-foreground.log'
    $h = Start-Process -FilePath $omniExe -WindowStyle Hidden -PassThru `
        -ArgumentList @('host', '--server', "http://127.0.0.1:$Port", '--no-open', '--non-interactive') `
        -RedirectStandardOutput $hostLog -RedirectStandardError "$hostLog.err"
    @{ server = $s.Id; host = $h.Id; url = "http://127.0.0.1:$Port" } | ConvertTo-Json | Set-Content $pidFile -Encoding utf8
    Write-Host "UI http://127.0.0.1:$Port  server pid $($s.Id)  host pid $($h.Id)  (pids: $pidFile)"
}

if ($Stop) {
    $pidFile = Join-Path $Runtime 'falsify-pids.json'
    if (Test-Path $pidFile) {
        $p = Get-Content $pidFile -Raw | ConvertFrom-Json
        foreach ($id in $p.host, $p.server) {
            $proc = Get-Process -Id $id -ErrorAction SilentlyContinue
            # Only stop the omni processes this launcher recorded; children exit with them.
            if ($proc -and $proc.ProcessName -eq 'omni') { Stop-Process -Id $id; Write-Host "stopped $id" }
        }
        Remove-Item $pidFile
    }
    omni stop   # also stops any Omnigent-managed background server/daemons in this runtime dir
}
if ($Status) { omni server status }

if ($Live) {
    Assert-Omnigent
    & $OmniPython (Join-Path $Root 'scripts\run_live.py') --server "http://127.0.0.1:$Port" --demo-root (Join-Path $Root $RunsDir)
    if ($LASTEXITCODE) { throw "live session did not complete (exit $LASTEXITCODE); see the proof under $RunsDir\omnigent" }
}

if ($Run) {
    Assert-Omnigent
    if (-not $Prompt) { throw 'Pass -Prompt "<text>" for a bounded session.' }
    Push-Location $Root
    try { omni run $Agent --server "http://127.0.0.1:$Port" -p $Prompt }
    finally { Pop-Location }
}
